baseURL = "/"   # 后面可以改成你自己的域名
languageCode = "zh-cn"
title = "灵感大于语言的诗歌手册"
theme = "m10c"

# 站点描述
[params]
  author = "李走走"
  description = "诗歌、散文、内省与日常碎片"
  # avatar = "/images/avatar.jpg"     # 如果有头像可以取消注释

# 主导航
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "诗歌"
    url = "/categories/poetry/"
    weight = 10
  [[menu.main]]
    name = "散文"
    url = "/categories/prose/"
    weight = 20
  [[menu.main]]
    name = "评论"
    url = "/categories/review/"
    weight = 30
  [[menu.main]]
    name = "小说"
    url = "/categories/novel/"
    weight = 100

# 其他常用设置
[markup]
  [markup.goldmark.renderer]
    unsafe = true   # 允许在 markdown 里写 html（可选）

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  taxonomyTerm = ["HTML"]